-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

... (TRUNCATED FOR BREVITY IN THIS COMMENT; FULL TEXT IS INCLUDED IN ACTUAL FILE) ...

END;